// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKwj3sYWKgjj3J3Aqd74X_5Vw50nvD7J0',
    appId: '1:6662346253:web:78cee3040eda510053e744',
    messagingSenderId: '6662346253',
    projectId: 'khuwaab-real-estate-pro',
    authDomain: 'khuwaab-real-estate-pro.firebaseapp.com',
    storageBucket: 'khuwaab-real-estate-pro.appspot.com',
    measurementId: 'G-HEGY69P9N7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM7qVvIHv3ieTKTuUbd3MeQ-Wp0FYmVdM',
    appId: '1:6662346253:android:9aed36c8d7cb82a953e744',
    messagingSenderId: '6662346253',
    projectId: 'khuwaab-real-estate-pro',
    storageBucket: 'khuwaab-real-estate-pro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCycsQ9bjXBoow96B8QU42IfAgfA2ppHc',
    appId: '1:6662346253:ios:d5515cbb7bf1325b53e744',
    messagingSenderId: '6662346253',
    projectId: 'khuwaab-real-estate-pro',
    storageBucket: 'khuwaab-real-estate-pro.appspot.com',
    iosBundleId: 'com.example.kfyp2',
  );
}
